<?php
/**
 * AyriaPaymentV1Command
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APG API
 *
 * This is a [APG (Ayria Payment Gateway) API](https://api.ayria.club/docs/index.html#_apg_ayria_payment_gateway) SDK.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AyriaPaymentV1Command Class Doc Comment
 *
 * @category Class
 * @description A payment command to create a payment in Ayria platform
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class AyriaPaymentV1Command implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AyriaPaymentV1Command';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'referral_code' => 'int',
        'amount' => 'int',
        'payer_mobile' => 'string',
        'payer_name' => 'string',
        'description' => 'string',
        'payment_number' => 'string',
        'extra_data' => 'string',
        'issuer_must_verify_payment' => 'bool',
        'callback_url' => 'string',
        'kalas' => '\OpenAPI\Client\Model\AyriaPaymentV1KalaDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'referral_code' => 'int64',
        'amount' => 'int64',
        'payer_mobile' => null,
        'payer_name' => null,
        'description' => null,
        'payment_number' => null,
        'extra_data' => null,
        'issuer_must_verify_payment' => null,
        'callback_url' => null,
        'kalas' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referral_code' => 'referralCode',
        'amount' => 'amount',
        'payer_mobile' => 'payerMobile',
        'payer_name' => 'payerName',
        'description' => 'description',
        'payment_number' => 'paymentNumber',
        'extra_data' => 'extraData',
        'issuer_must_verify_payment' => 'issuerMustVerifyPayment',
        'callback_url' => 'callbackUrl',
        'kalas' => 'kalas'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'referral_code' => 'setReferralCode',
        'amount' => 'setAmount',
        'payer_mobile' => 'setPayerMobile',
        'payer_name' => 'setPayerName',
        'description' => 'setDescription',
        'payment_number' => 'setPaymentNumber',
        'extra_data' => 'setExtraData',
        'issuer_must_verify_payment' => 'setIssuerMustVerifyPayment',
        'callback_url' => 'setCallbackUrl',
        'kalas' => 'setKalas'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'referral_code' => 'getReferralCode',
        'amount' => 'getAmount',
        'payer_mobile' => 'getPayerMobile',
        'payer_name' => 'getPayerName',
        'description' => 'getDescription',
        'payment_number' => 'getPaymentNumber',
        'extra_data' => 'getExtraData',
        'issuer_must_verify_payment' => 'getIssuerMustVerifyPayment',
        'callback_url' => 'getCallbackUrl',
        'kalas' => 'getKalas'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['referral_code'] = $data['referral_code'] ?? null;
        $this->container['amount'] = $data['amount'] ?? null;
        $this->container['payer_mobile'] = $data['payer_mobile'] ?? null;
        $this->container['payer_name'] = $data['payer_name'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['payment_number'] = $data['payment_number'] ?? null;
        $this->container['extra_data'] = $data['extra_data'] ?? null;
        $this->container['issuer_must_verify_payment'] = $data['issuer_must_verify_payment'] ?? null;
        $this->container['callback_url'] = $data['callback_url'] ?? null;
        $this->container['kalas'] = $data['kalas'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['referral_code'] === null) {
            $invalidProperties[] = "'referral_code' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['payer_mobile'] === null) {
            $invalidProperties[] = "'payer_mobile' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets referral_code
     *
     * @return int
     */
    public function getReferralCode()
    {
        return $this->container['referral_code'];
    }

    /**
     * Sets referral_code
     *
     * @param int $referral_code Payee referral code
     *
     * @return self
     */
    public function setReferralCode($referral_code)
    {
        $this->container['referral_code'] = $referral_code;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount Total price in Riyal currency
     *
     * @return self
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets payer_mobile
     *
     * @return string
     */
    public function getPayerMobile()
    {
        return $this->container['payer_mobile'];
    }

    /**
     * Sets payer_mobile
     *
     * @param string $payer_mobile Payer mobile number
     *
     * @return self
     */
    public function setPayerMobile($payer_mobile)
    {
        $this->container['payer_mobile'] = $payer_mobile;

        return $this;
    }

    /**
     * Gets payer_name
     *
     * @return string|null
     */
    public function getPayerName()
    {
        return $this->container['payer_name'];
    }

    /**
     * Sets payer_name
     *
     * @param string|null $payer_name Payer name
     *
     * @return self
     */
    public function setPayerName($payer_name)
    {
        $this->container['payer_name'] = $payer_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description for payment
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets payment_number
     *
     * @return string|null
     */
    public function getPaymentNumber()
    {
        return $this->container['payment_number'];
    }

    /**
     * Sets payment_number
     *
     * @param string|null $payment_number Payment number (external)
     *
     * @return self
     */
    public function setPaymentNumber($payment_number)
    {
        $this->container['payment_number'] = $payment_number;

        return $this;
    }

    /**
     * Gets extra_data
     *
     * @return string|null
     */
    public function getExtraData()
    {
        return $this->container['extra_data'];
    }

    /**
     * Sets extra_data
     *
     * @param string|null $extra_data Extra data related to payment
     *
     * @return self
     */
    public function setExtraData($extra_data)
    {
        $this->container['extra_data'] = $extra_data;

        return $this;
    }

    /**
     * Gets issuer_must_verify_payment
     *
     * @return bool|null
     */
    public function getIssuerMustVerifyPayment()
    {
        return $this->container['issuer_must_verify_payment'];
    }

    /**
     * Sets issuer_must_verify_payment
     *
     * @param bool|null $issuer_must_verify_payment Set it to 'true' if you want to verify payment
     *
     * @return self
     */
    public function setIssuerMustVerifyPayment($issuer_must_verify_payment)
    {
        $this->container['issuer_must_verify_payment'] = $issuer_must_verify_payment;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url Useful for when you want to have dynamic callback url
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets kalas
     *
     * @return \OpenAPI\Client\Model\AyriaPaymentV1KalaDTO[]|null
     */
    public function getKalas()
    {
        return $this->container['kalas'];
    }

    /**
     * Sets kalas
     *
     * @param \OpenAPI\Client\Model\AyriaPaymentV1KalaDTO[]|null $kalas kalas
     *
     * @return self
     */
    public function setKalas($kalas)
    {
        $this->container['kalas'] = $kalas;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


